{% set name = "nifti-mrs" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nifti_mrs-{{ version }}.tar.gz
  sha256: f1303b941332091fcc4b37f5861efeca680f491e2fd3d1a55732775dbdb2e7b7

build:
  entry_points:
    - mrs_tools = mrs_tools:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - versioneer
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - nibabel
    - fslpy

test:
  imports:
    - nifti_mrs
  commands:
    - pip check
    - mrs_tools --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wtclarke/nifti_mrs_tools
  summary: Software tools for the NIfTI-MRS data format
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vkarlaftis
    - wtclarke
