{% set name = "nifti-mrs" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nifti_mrs-{{ version }}.tar.gz
  sha256: b1d2c56615313f499e714aa3f4b6b2b43be1e1940057fa22234b3fed429abdcb

build:
  entry_points:
    - mrs_tools = mrs_tools:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - versioneer
    - pip
  run:
    - python >=3.7
    - numpy
    - nibabel
    - fslpy

test:
  imports:
    - nifti_mrs
  commands:
    - pip check
    - mrs_tools --help
  requires:
    - pip

about:
  home: https://github.com/wtclarke/nifti_mrs_tools
  summary: Software tools for the NIfTI-MRS data format
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wtclarke
