{% set name = "nifti-mrs" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nifti_mrs-{{ version }}.tar.gz
  sha256: 419e7e81b43d40fbc04cdf0174967c2d800b73913879bf0358d6e92d4ca45bed

build:
  entry_points:
    - mrs_tools = mrs_tools:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - versioneer
    - pip
  run:
    - python >=3.7
    - numpy
    - nibabel
    - fslpy

test:
  imports:
    - nifti_mrs
  commands:
    - pip check
    - mrs_tools --help
  requires:
    - pip

about:
  home: https://github.com/wtclarke/nifti_mrs_tools
  summary: Software tools for the NIfTI-MRS data format
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wtclarke
