{% set name = "nifti-mrs" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nifti_mrs-{{ version }}.tar.gz
  sha256: ddd553f604b7e0254d395fbd38ee18ddbcf71d7acd9aec82ae897c6f6d024b19

build:
  entry_points:
    - mrs_tools = mrs_tools:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - versioneer
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy
    - nibabel
    - fslpy

test:
  imports:
    - nifti_mrs
  commands:
    - pip check
    - mrs_tools --help
  requires:
    - pip

about:
  home: https://github.com/wtclarke/nifti_mrs_tools
  summary: Software tools for the NIfTI-MRS data format
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wtclarke
